### PR TITLE
fix(gazelle): handle auto-included __init__.py when generating py_binary targets.

### LINKED ISSUE #3729: Gazelle: conflict with per-file generation, `python_generation_mode_per_file_include_init`, and `py_binary` targets
# 🐞 bug report

### Affected Rule

Gazelle

### Is this a regression?

No

### Description

When using the following configuration:
```
# gazelle:python_generation_mode file
# gazelle:python_generation_mode_per_file_include_init true
```

Gazelle attempts to generate a `py_binary` containing each module with an `if __name__ == '__main__'`, as well as a `py_library` with the same name containing just `__init__.py`.

See here: https://github.com/bazel-contrib/rules_python/blob/ccdfc8a7e6aa888e88bdbaee141eceef7a7611e4/gazelle/python/generate.go#L276-L281

Generation logic removes the executable module from `srcs`, relying on `srcs` being empty later on to skip generating a library. But with `__init__.py` added, `srcs` is never empty.

## 🔬 Minimal Reproduction

I will post a PR with an updated test case and a fix.

## 🔥 Exception or Error

Gazelle complains about conflicting targets with the same name.

### PR DESCRIPTION
**Pull request by jvolkman**
Fixes binary target generation when using per-file mode and automatically 
including __init__.py files.

Fixes #3729

### CODE REVIEW

File: gazelle/python/generate.go [hunk 1]
```diff
@@ -258,6 +258,10 @@ func (py *Python) GenerateRules(args language.GenerateArgs) language.GenerateRes
 	// Create a validFilesMap of mainModules to validate if python macros have valid srcs.
 	validFilesMap := make(map[string]struct{})
 
+	// Determine whether we have an __init__.py file in this package and whether we'll implicitly include it in srcs.
+	hasInit, nonEmptyInit := hasLibraryEntrypointFile(args.Dir)
+	autoIncludeInit := cfg.PerFileGenerationIncludeInit() && hasInit && nonEmptyInit
```
[the remark this answers is not in the document]
Comment (jvolkman) [reply gazelle/python/generate.go]: Done. Thanks Gemini!

File: gazelle/python/generate.go [hunk 2]
```diff
@@ -258,6 +258,15 @@ func (py *Python) GenerateRules(args language.GenerateArgs) language.GenerateRes
 	// Create a validFilesMap of mainModules to validate if python macros have valid srcs.
 	validFilesMap := make(map[string]struct{})
 
+	// Determine whether we have an __init__.py file in this package and whether we'll implicitly include it in srcs.
+	var nonEmptyInit bool
```
Comment (dougthor42) [inline gazelle/python/generate.go]: I've never been a fan of this negative boolean logic. Let's switch to positive booleans:

```go
var populatedInit bool
```

**Review by dougthor42 — COMMENTED** [review]
Oh, and please add a line to `CHANGELOG.md`

File: gazelle/python/generate.go (hunk 2 above)
Comment (jvolkman) [reply gazelle/python/generate.go]: Named it `hasPopulatedInit` to match the existing `hasInit`.

**Review by dougthor42 — APPROVED** [review]
